name: lint

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: lint repository
        run: python scripts/lint_repo.py
